---
title: "COVID-19 en Costa Rica"
output: 
  html_document:
    toc: true
    toc_float: true
---

```{r setup, include=FALSE}
library(data.table)
library(countrycode)
library(lubridate)
library(ggplot2)
library(scales)
library(ggiraph)
library(cowplot)
library(sf)
library(readxl)   
library(httr)
library(RColorBrewer)

Sys.setlocale(locale="es_ES.UTF-8")
formato_fecha <- "%d-%b"
fecha_hoy <- as.character(Sys.Date())
#fecha_hoy <- "2020-04-09"

paises <- c("Costa Rica", "Panama", "Ecuador", "Colombia", "Honduras", "Dominican Republic",
            "Peru", "Chile", "Uruguay", "Cuba", "Ecuador", "Mexico")

fun_cantones_resumen <- function(fecha_hoy){
  URL_excel <- paste0("http://geovision.uned.ac.cr/oges/archivos_covid/", 
                      substr(fecha_hoy, 6, 7), "_", substr(fecha_hoy, 9, 10), "/",
                      substr(fecha_hoy, 6, 7), "_", substr(fecha_hoy, 9, 10),"_EXCEL.xlsx")
  
  GET(URL_excel, write_disk(tf <- tempfile(fileext = ".xlsx")))
  sheets <- excel_sheets(tf)
  
  cantones_d_vec <- like(sheets, "\\d$")
  
  cantones_datos_list <- lapply(sheets[cantones_d_vec], 
                                function(X) read_excel(
                                  tf, sheet = X, range = "B5:C86", col_names = c("canton", "casos")))
  names(cantones_datos_list) <- sheets[cantones_d_vec]
  
  cantones_datos <- rbindlist(cantones_datos_list, idcol = "fecha")
  
  cantones_datos[, fecha := lubridate::ymd(paste0("2020_", fecha))]
  setorder(cantones_datos, -canton, fecha)
  cantones_datos[, nuevos_casos := casos - shift(casos, n = 1L, fill = 0, type = "lag"), by = canton]
  max_casos_cantones <- cantones_datos[, .(max_casos = max(casos)), by = canton]
  cantones_datos <- merge(cantones_datos, max_casos_cantones[max_casos > 0], by = "canton", all = FALSE)
  cantones_datos[
    , ID := seq_len(.N)
  ][
    nuevos_casos < 0, nuevos_casos := 0
  ]
  
  resumen_d_vec <- like(sheets, "^\\d_\\w*")
  resumen_datos_list <- lapply(sheets[resumen_d_vec],
                               function(X) read_excel(
                                 tf, sheet = X, skip = 2, col_names = TRUE))
  
  resumen_datos_list <- lapply(resumen_datos_list, function(x) x[!is.na(x$"...2"), ])
  
  resumen_datos <- as.data.table(do.call(cbind, resumen_datos_list))
  resumen_col_vec <- like(colnames(resumen_datos), "\\d{4}$")
  resumen_col_vec[2] <- TRUE
  resumen_datos <- resumen_datos[1:26, ..resumen_col_vec]
  setnames(resumen_datos, 1, "info")
  
  resumen_datos[resumen_datos == "nd"] <- NA
  resumen_datos <- resumen_datos[, lapply(.SD, as.numeric), by=info]
  resumen_datos <- melt(resumen_datos,
                        id.vars = "info",
                        variable.name = "fecha",
                        value.name = "casos")
  resumen_datos[, fecha := lubridate::dmy(fecha)]
  setorder(resumen_datos, info, fecha)
  resumen_datos[, cambio_diario := casos - shift(casos, n = 1L, fill = 0, type = "lag"),
                by = info
  ][
    , ID := .I
  ]
  
  cant_resum <- list()
  cant_resum$resumen <- resumen_datos
  cant_resum$cantones <- cantones_datos
  
  return(cant_resum)
}

fun_paises <- function(fecha_hoy, paises){
  covid19_contagios <- fread("https://raw.githubusercontent.com/CSSEGISandData/COVID-19/master/csse_covid_19_data/csse_covid_19_time_series/time_series_covid19_confirmed_global.csv", header=T)[
    , tipo := "contagios"
  ]
  
  covid19_recuperados <- fread("https://raw.githubusercontent.com/CSSEGISandData/COVID-19/master/csse_covid_19_data/csse_covid_19_time_series/time_series_covid19_recovered_global.csv", header=T)[
    , tipo := "recuperados"
  ]
  
  covid19_decesos <- fread("https://raw.githubusercontent.com/CSSEGISandData/COVID-19/master/csse_covid_19_data/csse_covid_19_time_series/time_series_covid19_deaths_global.csv", header=T)[
    , tipo := "decesos"
  ]
  
  covid19 <- rbindlist(list(covid19_contagios, covid19_decesos, covid19_recuperados))
  
  covid19_tidy <- melt(covid19,
                       id.vars = c("Province/State", "Country/Region", "Lat", "Long", "tipo"),
                       variable.name = "fecha",
                       value.name = "casos")[
                         , `:=`(fecha = mdy(fecha),
                                cod_pais = countrycode(`Country/Region`, 
                                                       origin = "country.name", destination = "iso3c"),
                                pais = countrycode(`Country/Region`, 
                                                   origin = "country.name", destination = "un.name.es"))
                       ]
  
  t_cntrys <- covid19_tidy[`Country/Region` %in% paises
  ][
    , .(casos = sum(casos, na.rm = T)),
    by = c("Country/Region", "fecha", "tipo", "cod_pais", "pais") 
  ][
    , ID := seq_len(.N)
  ]
  
  return(t_cntrys)
}

t_cntrys <- fun_paises(fecha_hoy, paises)
fecha_min <- t_cntrys[casos == 1, .SD[which.min(fecha)]]$fecha

fecha_diauno <- t_cntrys[
  tipo == "contagios" & casos > 0 ][
    , .SD[which.min(fecha)], by = "Country/Region" ][
      , .(`Country/Region`,
          fecha_diauno = fecha)]
  
t_gt_diauno <- fecha_diauno[
  t_cntrys, on=c(`Country/Region` = "Country/Region") ][
    fecha >= fecha_diauno][
      order(`Country/Region`, tipo, fecha) ][
        casos > 0, 
        `:=`(num_dia = as.integer(difftime(fecha, fecha_diauno, units = "days") + 1),
             nuevos_casos = casos - shift(casos, fill = 0),
             prct_dif_casos = round((casos - shift(casos, fill = 0))/(shift(casos, fill = NA))*100, 1)), 
        by = c("Country/Region", "tipo", "cod_pais", "pais") ]

t_gt_diauno[is.na(t_gt_diauno)] <- 0

max_dia_CR <- max(t_gt_diauno[`Country/Region` == "Costa Rica" & tipo == "contagios", num_dia])

setorder(t_gt_diauno, -`Country/Region`, fecha)
t_gt_diauno$`Country/Region` <- factor(t_gt_diauno$`Country/Region`, 
                                       levels=unique(t_gt_diauno$`Country/Region`))

breaks = c(1, 10, 100, 1000)

poblacion <- fread("WPP2019_TotalPopulationBySex.csv")[
  Time == 2020 & Variant == "Medium",
  .(Location, 
    PopTotal = as.integer(PopTotal*1000))]

tb_general <- merge(t_gt_diauno, poblacion, by.x = "Country/Region", by.y = "Location", all.x = TRUE)

tb_general[
  , casos_10k := casos*100000/PopTotal]

cant_resumen <- fun_cantones_resumen(fecha_hoy)
cantones_tidy <- cant_resumen$cantones

cantones_simp <- st_read("cantones.geojson")

cantones_tidy_mapa <- merge(cantones_simp, cantones_tidy, by = "canton")

provincias = merge(cantones_tidy, cantones_simp, by = "canton")[
  , .(casos = sum(casos)), by = c("provincia", "fecha")
][
  , max_casos := max(casos), by = c("provincia")
]

setorder(provincias, provincia)

provincias$provincia <- factor(provincias$provincia, levels=unique(provincias$provincia))

CR_detalles <- cant_resumen$resumen

```

### Costa Rica en la región

```{r, echo = FALSE, fig.align="center"}
cols <- c("#a6cee3", "#1f78b4", "#b2df8a", "#33a02c", "#fb9a99", "#e31a1c",
"#fdbf6f", "#ff7f00", "#cab2d6", "#6a3d9a","#CDBE70" ,"#b15928")
# brewer.pal(12, "Paired")

col_paises <- colorRampPalette(cols)(length(paises))


g1 <- ggplot(t_cntrys[tipo == "contagios" & 
                        #fecha >= fecha_min & 
                        fecha >= dmy("08/03/2020") &
                        casos > 0], 
       aes(x = fecha, y = casos, group = pais, col = pais)) + 
  geom_line(alpha = 0.5) +
  geom_point(size = 0.7, alpha = 0.7) +
  # scale_y_continuous(labels=comma) +
  scale_y_continuous(trans = "log10") +
  scale_x_date(date_breaks = "4 days", 
               minor_breaks = NULL,
               date_labels = formato_fecha) +
  # scale_colour_brewer(palette = "Dark2") +
  scale_color_manual(values = col_paises) +
  theme_light() +
  labs(x = "",
       y = "Casos reportados",
       col = "",
       title = "",
       subtitle = "") +
  theme(axis.text.x=element_text(angle=60, hjust=1),
        legend.position = "none",
        plot.margin = unit(c(0,5,0,0), "mm"))

g1_g <- g1 + 
  geom_point_interactive(
    aes(tooltip = paste0(
      pais, "\n", 
      paste0(day(fecha), " de ", month(fecha, label=TRUE, abbr=FALSE)), "\n", 
      casos," casos"),
      data_id = ID), size = 0.75)

g2 <- ggplot(t_gt_diauno[num_dia <= max_dia_CR & tipo == "contagios"], 
       aes(x = num_dia, y = casos, group = pais, col = pais, )) + 
  geom_line(linetype = 2, size = 0.5, alpha = 0.5) +
  geom_point(size = 0.7, alpha = 0.7) +
  scale_y_continuous() +
  scale_x_continuous(minor_breaks = NULL) + 
  #geom_smooth(method="lm", formula= (y ~ exp(2)), se=FALSE, color=1) +
  # scale_colour_brewer(palette = "Dark2") +
  scale_color_manual(values = col_paises) +
  theme_light() +
  labs(x = "Días luego de primera detección",
       y = "Casos reportados",
       col = "",
       title = "",
       subtitle = "") +
  # guides(color = guide_legend(nrow = 1)) +
  theme(legend.position = "none",
        plot.margin = unit(c(0,0,0,0), "mm"))

g2_g <- g2 + 
  geom_point_interactive(
    aes(tooltip = paste0(
    pais, "\n", 
    paste0(day(fecha), " de ", month(fecha, label=TRUE, abbr=FALSE)), "\n", 
    casos," casos"), 
    data_id = ID), size = 0.75)

g4 <- ggplot(tb_general[tipo == "contagios" & 
                          #fecha >= fecha_min &
                          fecha >= dmy("08/03/2020")], 
       aes(x = fecha, y = casos_10k, group = pais, col = pais)) + 
  geom_line(alpha = 0.7) +
  geom_point(size = 0.3) +
  #scale_y_continuous(trans = "log10") +
  scale_x_date(date_breaks = "4 days", 
               minor_breaks = NULL,
               date_labels =  formato_fecha) +
  # scale_colour_brewer(palette = "Dark2") +
  scale_color_manual(values = col_paises) +
  theme_light() +
  labs(x = "",
       y = "Casos por cada 100,000 habitantes",
       col = "",
       title = "",
       subtitle = "") +
  theme(axis.text.x=element_text(angle=60, hjust=1),
        legend.position = "none",
        plot.margin = unit(c(0,0,0,5), "mm"))

g4_g <- g4 + 
  geom_point_interactive(
    aes(tooltip = paste0(
      pais, "\n", 
      paste0(day(fecha), " de ", month(fecha, label=TRUE, abbr=FALSE)), "\n", 
      round(casos_10k,1)," casos/10,000 hab."),
      data_id = ID), size = 0.75)

legend_paises <- get_legend(
  g1 + 
    guides(color = guide_legend(nrow = 2)) +
    theme(legend.position = "bottom",
          # legend.box="vertical", legend.margin=margin(),
          plot.margin = unit(c(0,0,0,0), "mm")))

alineados <- align_plots(g1_g, g2_g, legend_paises, align = 'v', axis = 'l')
linea_2 <- alineados[[2]]

combinado <- plot_grid(
  plot_grid(alineados[[1]], g4_g), linea_2,
  ncol = 1, rel_heights = c(1, 1))

girafe(ggobj = plot_grid(
  alineados[[3]],
  combinado,
  ncol = 1, rel_heights = c(.1, 2)),
  options = list(opts_tooltip(use_fill = TRUE,
                              offx = 10, offy = 10,
                              css = "color:white;"),
                 opts_hover(css = "stroke:orange;
                 stroke-width:2;"),
                 opts_toolbar(saveaspng = FALSE)),
  width_svg = 8, height_svg = 8)

```

### Casos en Costa Rica

```{r echo=FALSE, message=FALSE, warning=FALSE, fig.align="center"}
v_resumenDiario_CR <- ggplot(
  CR_detalles[ info %in% c("Confirmados", "Recuperados" , "Fallecidos", "Descartados")], 
  aes(x = fecha, y = cambio_diario)) +
  geom_col_interactive(
        aes(tooltip = paste0(day(fecha), " de ", 
                         month(fecha, label=TRUE, abbr=FALSE), "\n", 
                         cambio_diario, " casos"),
      data_id = ID)) +
  facet_grid(rows = vars(info), scales = "free") +
  scale_y_continuous(breaks = function(x) unique(floor(pretty(seq(0, (max(x) + 1) * 1.1))))) +
  scale_x_date(date_breaks = "4 days", 
               minor_breaks = NULL,
               date_labels =  formato_fecha) + 
  theme_light() +
  labs(x = "",
       y = "Casos reportados al día",
       title = "Casos por día") + 
    theme(axis.text.x=element_text(angle=60, hjust=1),
        # legend.position="bottom", legend.box = "horizontal", 
        plot.margin = unit(c(5,0,0,5), "mm"),
        strip.text.x = element_text(size = 6))

v_resumenAcum_CR <- ggplot(
  CR_detalles[
    info %in% c("Confirmados", "Recuperados" , "Fallecidos", "Descartados")], 
  aes(x = fecha, y = casos)) +
  geom_line() +
  geom_point_interactive(
    aes(tooltip = paste0(day(fecha), " de ", 
                         month(fecha, label=TRUE, abbr=FALSE), "\n", 
                         casos, " casos"),
        data_id = ID),
    size = 0.5) +
  facet_grid(rows = vars(info), scales = "free") +
  scale_y_continuous(breaks = function(x) unique(floor(pretty(seq(0, (max(x) + 1) * 1.1))))) +
  scale_x_date(date_breaks = "4 days", 
               minor_breaks = NULL,
               date_labels =  formato_fecha) + 
  theme_light() +
  labs(x = "",
       y = "Número de casos",
       title = "Casos acumulados") + 
  theme(axis.text.x=element_text(angle=60, hjust=1),
        # legend.position="bottom", legend.box = "horizontal", 
        plot.margin = unit(c(5,5,0,0), "mm"),
        strip.text.x = element_text(size = 6))

girafe(ggobj = plot_grid(v_resumenAcum_CR, v_resumenDiario_CR),
       options = list(
          opts_toolbar(saveaspng = FALSE),
          opts_hover(css = "fill:orange;stroke:orange;stroke-width:1;")),
       width_svg = 7, height_svg = 5
       )

```

```{r echo=FALSE, message=FALSE, warning=FALSE, fig.align="center"}
branded_colors <- list(
  "blue"   = "#00798c",
  "red"    = "#d1495b",
  "yellow" = "#edae49",
  "green"  = "#66a182",
  "navy"   = "#2e4057", 
  "grey"   = "#8d96a3"
)

branded_pal <- function(
  primary = "blue", 
  other = "grey", 
  direction = 1
) {
  stopifnot(primary %in% names(branded_colors))
  
  function(n) {
    if (n > 6) warning("Branded Color Palette only has 6 colors.")
    
    if (n == 2) {
      other <- if (!other %in% names(branded_colors)) {
        other
      } else {
        branded_colors[other]
      }
      color_list <- c(other, branded_colors[primary])
    } else {
      color_list <- branded_colors[1:n]
    }
    
    color_list <- unname(unlist(color_list))
    if (direction >= 0) color_list else rev(color_list)
  }
}

scale_fill_branded_d <- function(
  primary = "blue", 
  other = "grey", 
  direction = 1, 
  ...
) {
  ggplot2::discrete_scale(
    "fill", "branded", 
    branded_pal(primary, other, direction), 
    ...
  )
}

scale_col_branded_d <- function(
  primary = "blue", 
  other = "grey", 
  direction = 1, 
  ...
) {
  ggplot2::discrete_scale(
    "colour", "branded", 
    branded_pal(primary, other, direction), 
    ...
  )
}

scale_fill_branded_d <- scale_fill_branded_d
scale_col_branded_d <- scale_col_branded_d

edades <- CR_detalles[info %in% c("Adultos", "Adultos Mayores", "Menores") &
                        fecha > lubridate::dmy("09/3/2020")]
hospitalizacion <- CR_detalles[info %in% c("Salón", "UCI") &
                        fecha > lubridate::dmy("09/3/2020")]
sexo <- CR_detalles[info %in% c("Mujeres", "Hombres") &
                        fecha > lubridate::dmy("09/3/2020")]

g_edades <- ggplot(edades,
       aes(x = fecha, y = casos, group = info, col = info)) +
  geom_line() +
  geom_point_interactive(
    aes(tooltip = paste0(
      paste0(day(fecha), " de ", month(fecha, label=TRUE, abbr=FALSE)), "\n",
      info, "\n",
      casos," casos"), 
      data_id = ID),
    size = 0.5) + 
  scale_y_continuous(limits = c(0, NA),
                     expand = c(0,3)) +
  scale_x_date(date_breaks = "1 week", 
               minor_breaks = NULL,
               date_labels = formato_fecha) +
  theme_light() +
  labs(x = "",
       y = "Casos acumulados",
       col = "") + 
  theme(axis.text.x=element_text(angle=60, hjust=1),
        # legend.key.width = unit(2,"mm"),
        legend.background = element_rect(fill=NULL, 
                                  size=0.5, linetype="solid"),
        legend.margin = unit(c(0,0,0,0), "mm"),
        legend.position = c(0.25, 0.75), 
        plot.margin = unit(c(5,5,0,0), "mm"))

g_sexo <- ggplot(sexo, 
       aes(x = fecha, y = casos, group = info, col = info)) +
  geom_line() +
  geom_point_interactive(
    aes(tooltip = paste0(
      paste0(day(fecha), " de ", month(fecha, label=TRUE, abbr=FALSE)), "\n", 
      info, "\n",
      casos," casos"), 
      data_id = ID),
    size = 0.5) +
  scale_col_branded_d(primary = "grey",
                       other = "orange") +
  scale_y_continuous(limits = c(0, NA),
                     expand = c(0,3)) +
  scale_x_date(date_breaks = "1 week", 
               minor_breaks = NULL,
               date_labels = formato_fecha) +
  theme_light() +
  labs(x = "",
       y = "Casos acumulados",
       col = "") + 
  theme(axis.text.x=element_text(angle=60, hjust=1),
        # legend.key.width = unit(2,"mm"),
        # legend.text = element_text(size=6),
        legend.margin = unit(c(0,0,0,0), "mm"),
        # legend.position = "bottom",
        legend.position = c(0.2, 0.8), 
        plot.margin = unit(c(5,0,0,5), "mm"))

g_hospi <- ggplot(hospitalizacion,
                  aes(x = fecha, y = casos, group = info, fill = info)) +
  geom_col_interactive(
    aes(tooltip = paste0(
      paste0(day(fecha), " de ", month(fecha, label=TRUE, abbr=FALSE)), "\n", 
      info, "\n",
      casos," casos"), 
      data_id = ID),
    position = position_dodge()) + 
  scale_fill_branded_d(other = "#a2d729") +
  scale_x_date(date_breaks = "4 days", 
               minor_breaks = NULL,
               date_labels = formato_fecha,
               limits = c(lubridate::dmy("30-3-2020"), NA)) +
  scale_y_continuous(limits = c(0, NA),
                     expand = c(0,0.2)) +
  theme_light() +
  labs(x = "",
       y = "Casos al día",
       fill = "Hospitalización:") + 
  theme(axis.text.x=element_text(angle=60, hjust=1),
        legend.key.width = unit(2,"mm"),
        legend.position = "bottom",
        plot.margin = unit(c(1,1,1,1), "mm"))

# alineados <- align_plots(g_edades, g_sexo, g_hospi, align = 'hv', axis = 'rl')

girafe(ggobj = plot_grid(g_edades, g_sexo, ncol = 2),
       options = list(
         opts_tooltip(use_fill = TRUE),
         opts_toolbar(saveaspng = FALSE),
         opts_hover(css = "fill:NULL;stroke:NULL;")),
       width_svg = 6.5, height_svg = 3)

girafe(ggobj = g_hospi,
       options = list(
         opts_tooltip(use_fill = TRUE),
         opts_toolbar(saveaspng = FALSE),
         opts_hover(css = "fill:NULL;stroke:NULL;")),
       width_svg = 6.5, height_svg = 3)

```

### Casos por cantón y provincia
```{r echo=FALSE, message=FALSE, warning=FALSE, fig.align="center"}
cant_geo <- cantones_tidy_mapa[
  cantones_tidy_mapa$fecha == fecha_hoy & 
    !is.na(cantones_tidy_mapa$casos) & 
    cantones_tidy_mapa$casos > 0, ]

cant_geo_cntrids <- st_centroid(cant_geo)

provincias_geo <- aggregate(cantones_simp[, "cod_canton"], 
                            by = list(cantones_simp$provincia),
                            FUN = max)

provincias_geo <- dplyr::rename(provincias_geo, provincia = Group.1)

provincias_mapa <-  merge(provincias_geo, provincias[fecha == fecha_hoy, ], by = "provincia")

g_mapa <- ggplot() +
  geom_sf(data = cantones_simp, fill = "gray", col = "white", lwd = 0.2, alpha = 0.5) +
  geom_sf(data = provincias_mapa, fill = NA, col = "white", lwd = 0.7) +
  geom_sf_text(data = provincias_mapa, aes(label = paste0(provincia, "\n",
                                                          casos, " casos")),
               alpha = 0.6,
               size = 2,
               check_overlap = TRUE) +
  geom_sf_interactive(data = cant_geo_cntrids, 
                      aes(size = casos,
                          tooltip = paste0("Provincia: ", provincia, "\n",
                                           "Cantón: ", canton, "\n",
                                           "Casos totales: ", casos),
                          data_id = ID),
                      col = "red", alpha = 0.3) +
  coord_sf(datum = NA) +
  theme_light() + 
  labs(x = "",
       y = "",
       size = "Casos",
       title = "",
       subtitle = "") +
  theme(panel.border = element_blank()) +
  scale_size_area()

girafe(ggobj = g_mapa,
  options = list(opts_hover(css = "fill:yellow;"),
                 opts_toolbar(saveaspng = FALSE),
                 opts_tooltip(css=("background-color:gray;color:white;padding:5px;border-radius:2px;"),
                              offx = 10, offy = 10)))

```

### Evolución de casos por provincia
```{r echo=FALSE, message=FALSE, warning=FALSE, fig.align="center"}
g_prov <- ggplot(provincias, aes(x = fecha, y = casos, fill = provincia)) +
  geom_col_interactive(
    aes(tooltip = paste0(provincia, "\n",
                         casos, " casos", 
                         " al ", day(fecha), " de ", 
                         month(fecha, label=TRUE, abbr=FALSE)),
      data_id = provincia)) +
  scale_x_date(date_breaks = "4 days", 
               minor_breaks = NULL,
               date_labels =  formato_fecha) +
  scale_fill_brewer(palette = "Set2") +
  theme_light() +
  labs(x = "",
       y = "Casos reportados",
       fill = "",
       title = "",
       subtitle = "") +
  theme(axis.text.x=element_text(angle=60, hjust=1),
        legend.position="bottom", legend.box = "horizontal", 
        plot.margin = unit(c(5,0,0,0), "mm"),
        legend.key.width = unit(2,"mm"),
        legend.key.size = unit(5, "mm")) +
  guides(color = guide_legend(nrow = 1))

girafe(ggobj = g_prov,
       options = list(
         opts_tooltip(use_fill = TRUE),
         opts_toolbar(saveaspng = FALSE),
         opts_hover(css = "fill:NULL;stroke:NULL;")),
       width_svg = 6, height_svg = 3.5)
```

### Evolución de casos por cantón
```{r, echo = FALSE, fig.align="center"}
cant_heatmap <- as.data.table(cantones_tidy_mapa)
setorder(cant_heatmap, -canton)
cant_heatmap$canton <- factor(cant_heatmap$canton, levels=unique(cant_heatmap$canton))

g_cant_1 <- ggplot(cant_heatmap, 
       aes(x = fecha, y = canton, fill = casos)) + 
  geom_tile(width=1, height=.8) +
  #geom_point(size = 0.4) +
  scale_x_date(date_breaks = "1 week", 
               minor_breaks = NULL,
               date_labels = formato_fecha,
               #limits = c(min(cantones_tidy$fecha), ymd(fecha_hoy)),
               sec.axis = dup_axis()) +
  # scale_colour_brewer(palette = "Dark2") +
  scale_fill_viridis_c(trans = "pseudo_log") +
  theme_light() +
  labs(x = "",
       y = "",
       fill = "",
       title = "",
       subtitle = "Casos acumulados") +
  theme(#axis.text.x = element_text(angle=60, hjust=1),
        #axis.text.y = element_text(size = 5),
        legend.position="left", legend.box = "vertical",
        legend.title = element_text(size = 10),
        legend.text = element_text(size = 6),
        plot.margin = unit(c(0,0,0,0), "mm")
        ) +
  guides(fill = guide_colourbar(barwidth = .5, barheight = 10))

g_cant_1_g <- g_cant_1 + 
  geom_tile_interactive(
    aes(tooltip = paste0(
      "Provincia: ", provincia, "\n",
      "Cantón: ", canton, "\n",
      day(fecha), " de ", month(fecha, label=TRUE, abbr=FALSE), "\n", 
      casos," casos totales", "\n",
      nuevos_casos," casos nuevos"),
      data_id = ID), 
    width=1, height=.8)

g_cant_2 <- ggplot(cant_heatmap, 
       aes(x = fecha, 
           y = canton, 
           fill = nuevos_casos)) + 
  geom_tile(width=1, height=.8) +
  #geom_point(size = 0.4) +
  scale_x_date(date_breaks = "1 week", 
               minor_breaks = NULL,
               date_labels = formato_fecha,
               #limits = c(min(cantones_tidy$fecha), ymd(fecha_hoy)),
               sec.axis = dup_axis()) +
  # scale_colour_brewer(palette = "Dark2") +
  # scale_y_discrete(position = "right") +
  scale_fill_viridis_c(option = "plasma", direction = 1, labels = number_format(accuracy = 1)) +
  theme_light() +
  labs(x = "",
       y = "",
       fill = "",
       title = "",
       subtitle = "Nuevos casos por día") +
  theme(#axis.text.x = element_text(angle=60, hjust=0.5),
        axis.text.y=element_blank(),
        legend.position="right", legend.box = "vertical",
        legend.title = element_text(size = 10),
        legend.text = element_text(size = 6),
        plot.margin = unit(c(0,0,0,0), "mm")) +
  guides(fill = guide_colourbar(barwidth = .5, barheight = 10))

g_cant_2_g <- g_cant_2 + 
  geom_tile_interactive(
    aes(tooltip = paste0(
      "Provincia: ", provincia, "\n",
      "Cantón: ", canton, "\n",
      day(fecha), " de ", month(fecha, label=TRUE, abbr=FALSE), "\n",
      casos," casos totales", "\n",
      nuevos_casos," casos nuevos"),
      data_id = ID), width=.9, height=.8)

girafe(ggobj = plot_grid(g_cant_1_g, g_cant_2_g, rel_widths = c(1, .75)), 
       options = list(opts_toolbar(saveaspng = FALSE),
                      opts_hover(css = "fill:transparent;
                                 stroke:red;
                                 stroke-width:2"),
                      opts_tooltip(offx = 15, offy = 15)),
       width_svg = 8, height_svg = 10)
```

Elaborado por gds506@gmail.com con datos diarios del [CSSE del John Hopkins University](https://github.com/CSSEGISandData/COVID-19) y del [Ministerio de Salud de Costa Rica](http://geovision.uned.ac.cr/oges/). 


